version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user --no-cache-dir -r requirements.txt
      - python/save-cache
      - run:
          name: Run Tests
          command: ~/.local/bin/pytest

workflows:
  main:
    jobs:
      - build-and-test